### ISSUE TITLE
isTesting not working on iOS

### ISSUE THREAD

**Issue by Galaen** [appfeel/admob-google-cordova#68]
Hi,

I'm testing your plugin at the moment and it seems good but I have an issue with the "isTesting" option.
When I set it to "true", I can see the "testing" interstitial on Android in my App but nothing on iOS.
If I set it to "false" I can see the Interstitial on both iOS and Android (real one)
Did I miss something ?

Here the last options I'm using:

 ```
       admob.setOptions({
          isTesting:            true,
        
          overlap:              true,
          offsetStatusBar:      false,
//          adSize:               admob.AD_SIZE.SMART_BANNER,
//          bannerAtTop:          false,
          autoShowBanner:       false,
          autoShowInterstitial: false,
          
          publisherId:        admobid.banner,
          interstitialAdId:   admobid.interstitial
          //tappxIdiOS:       "/XXXXXXXXX/Pub-XXXX-iOS-IIII",
          //tappxIdAndroid:   "/XXXXXXXXX/Pub-XXXX-Android-AAAA",
          //tappxShare:         0.0
        });
```

I'm testing it with a phonegap app with your "phonegap-admob" plugin

Thanks

**Comment by miqmago** [comment]
It's probably because you have advertising tracking disabled on this ios device.

Can you debug in XCode? If yes, you can place a breakpoint at these lines:

- https://github.com/appfeel/admob-google-cordova/blob/master/src/ios/CDVAdMobAds.m#L688
- https://github.com/appfeel/admob-google-cordova/blob/master/src/ios/CDVAdMobAds.m#L699

and see if the debugger is correctly detecting the `isTesting` flag and if the device id is correct. When you set `isTesting` to false, you can see your device id in the XCode console in a message like:

```
<Google> To get test ads on this device, call: request.testDevices = @[ @"49cd348fa9c01223dd293bcce92f1e08" ];
```

Please let me know if the console device id and the `admobDeviceId` obtained at line 698 are the same.

**Comment by Galaen** [comment]
I'm using the phonegap build for iOS and don't have access to XCode yet.
But you were right about the advertising tracking disabled.
I've removed the limited tracking option and I can now see testing ads on the iOS device.

Thanks
